pipeline {
   agent any
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
           echo 'Building...'
        }
        stage('Test') {
            echo 'Testing..'
        }
        stage('Deploy') {
            echo 'Deploy'
        }
    }
}
