pipeline {
   agent any
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
           steps{
           echo 'Building....'
           }
        }
        stage('Testing') {
           steps{
            echo 'Testing..'
           }
        }
        stage('Deployed') {
           steps{
            echo 'Deploy..'
           }
        }
    }
}
